### ISSUE TITLE
Problem with cinterop (NSBundle.h:90:122: error: expected ';' after method prototype)

### ISSUE THREAD

**Issue by developer--** [SalomonBrys/Demo-SwiftLib-in-KMMLib#3]
At first with your cloned repo I got some errors with cinterop tasks
which I have resolved by adding 
```
tasks.withType(org.jetbrains.kotlin.gradle.tasks.CInteropProcess::class.java) {
    settings.compilerOpts("-DNS_FORMAT_ARGUMENT(A)= -D_Nullable_result=_Nullable")
}
```
But now I got another issue and maybe you have an idea what can be done?

```
> Task :cinteropSwiftChachaPolyIosArm64 FAILED
Exception in thread "main" java.lang.Error: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSBundle.h:90:122: error: expected ';' after method prototype
        at org.jetbrains.kotlin.native.interop.indexer.UtilsKt.ensureNoCompileErrors(Utils.kt:152)
        at org.jetbrains.kotlin.native.interop.indexer.IndexerKt.indexDeclarations(Indexer.kt:1003)
        at org.jetbrains.kotlin.native.interop.indexer.IndexerKt.buildNativeIndexImpl(Indexer.kt:992)
        at org.jetbrains.kotlin.native.interop.indexer.NativeIndexKt.buildNativeIndex(NativeIndex.kt:91)
        at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processCLib(main.kt:266)
        at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.interop(main.kt:74)
        at org.jetbrains.kotlin.cli.utilities.InteropCompilerKt.invokeInterop(InteropCompiler.kt:45)
        at org.jetbrains.kotlin.cli.utilities.MainKt.mainImpl(main.kt:19)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:41)

FAILURE: Build failed with an exception.

```

**Comment by SvyatoslavScherbina** [comment]
>     settings.compilerOpts("-DNS_FORMAT_ARGUMENT(A)= -D_Nullable_result=_Nullable")

It should be

>     settings.compilerOpts("-DNS_FORMAT_ARGUMENT(A)=", "-D_Nullable_result=_Nullable")

Also, https://github.com/KodeinKoders/playground-SwiftLib-in-KMMLib/blob/95d7aed405543a59e4a575691c638bf9fce9e2ff/build.gradle.kts#L2
Kotlin 1.4.30 is more than one year old, please update to a recent version, e.g. 1.6.21. You won't need these workarounds after the update.

**Comment by developer--** [comment]
Thanks for the response in my case I had an updated versions (1.6.20)

Fix was in that 
```
tasks.withType(org.jetbrains.kotlin.gradle.tasks.CInteropProcess::class.java)
    .matching { it.name.contains("cinteropAbly") }
    .configureEach {
        settings.compilerOpts("-DNS_FORMAT_ARGUMENT(A)= -D_Nullable_result=_Nullable")
    }
```

**Comment by SvyatoslavScherbina** [comment]
>         settings.compilerOpts("-DNS_FORMAT_ARGUMENT(A)= -D_Nullable_result=_Nullable")

You don't need this with Kotlin 1.6.21. Please try removing it. And using it like this, without splitting to two different arguments, is still incorrect.

**Comment by developer--** [comment]
Hm, you are right, strange thing is that it wasn't working without that, but now it works 😌
